# Generated by Django 5.1 on 2024-08-13 19:50

import student.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        validators=[student.models.validate_name],
                        verbose_name="Student Name",
                    ),
                ),
                (
                    "age",
                    models.IntegerField(
                        validators=[student.models.validate_age],
                        verbose_name="Student Age",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        max_length=255,
                        validators=[student.models.validate_address],
                        verbose_name="Student Address",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("F", "F"),
                        ],
                        max_length=1,
                        null=True,
                        verbose_name="Student Grade",
                    ),
                ),
                (
                    "major",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        validators=[student.models.validate_major],
                        verbose_name="Student Major",
                    ),
                ),
            ],
        ),
    ]
